[IMP]purchase: Format currency on the dashboard of Purchase List View
Viindoo/odoo pull request #107
Opened 2021-12-03 08:19 UTC by lathuat1997

Định dạng lại tiền tệ trên phần Dashboard của List View mua hàng

Ticket: https://viindoo.com/web#active_id=3502&cids=1&id=3502&model=helpdesk.ticket&menu_id=

2021-12-03 10:51 UTC, davidtranhp requested changes

2021-12-03 10:51 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
@lathuat1997 Fix ở phía Odoo nhé em

CC @leotranviindoo

2021-12-03 12:54 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
Em có thể dùng `format_amount(env, amount, currency, lang_code)` thì không phải if else cái currency.position.

2021-12-04 01:54 UTC, lathuat1997 commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
Vâng anh, em sẽ chỉnh lại ạ

2021-12-04 03:32 UTC, lathuat1997 commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
@davidtranhp phần if else kia là để em bỏ phần ký hiệu của tiền tệ đi, vì trên phần label đã có ký hiệu tiền tệ rồi
Nếu dùng format_amount() thì vẫn có ký hiệu này anh ạ

2021-12-04 03:59 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
Cơ mà anh vẫn chưa hiểu có vấn đề gì ở đây. Các đơn mua mỗi đơn có thể có tiền tệ khác nhau. Nếu bỏ ký hiệu tiền tệ đi thì làm sao mà biết được là tiền tệ gì?

2021-12-04 04:02 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
Anh xem qua code của chố này thì anh thấy nếu có vấn đề thì chắc sẽ là vấn đề về đa công ty ở cái chỗ dashboard. Có vẻ như code này mới chỉ lấy cho company hiện hành chứ chưa tính đến người dùng select nhiều company.

2021-12-04 04:21 UTC, lathuat1997 commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
![purchase2](https://user-images.githubusercontent.com/65999461/144696444-d0d3bad7-bb69-44a1-9ef5-c3994b52ce2c.png)

Odoo14 mới bổ sung 1 cái dashboad trên phần list view của Đơn mua
Phần hiển thị số tiền trên dashboard chưa có dấu phân cách hàng nghìn, nên em làm PR này để giải quyết vấn đề đó ạ, còn trên `label` của số tiền đã có ký hiệu của tiền tệ rồi nên em bỏ ký hiệu ở phần `số` đi anh ạ.

2021-12-07 10:25 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
@lathuat1997 chú fix ở bên Odoo nhé.
CC @leotranviindoo

2021-12-07 11:10 UTC, lathuat1997 commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
vâng anh, em tạo PR cho odoo rồi ạ

2021-12-07 13:09 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
Anh thấy Odoo nó có comment đấy

2021-12-07 13:10 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
Mà chú để lại cái ký hiệu tiền tệ cũng chẳng sao mà. Cho code nó gọn, dễ được merge.

2021-12-07 13:16 UTC, lathuat1997 commented on addons/purchase/models/purchase.py
> +            result['all_total_last_7_days'] = result['all_total_last_7_days'].split(' ')[-1]
vâng anh, em sẽ chỉnh lại ạ

2021-12-07 14:19 UTC, leotranviindoo commented
@lathuat1997 lần trước anh đăng ký sai email của chú với Odoo (thiếu chữ `l`) nên PR https://github.com/odoo/odoo/pull/80938 của chú đang chết kịch bản test CLA của Odoo. 

Anh có PR update lại ở https://github.com/odoo/odoo/pull/80976 nhé

2021-12-07 14:22 UTC, leotranviindoo commented
> @lathuat1997 lần trước anh đăng ký sai email của chú với Odoo (thiếu chữ `l`) nên PR [odoo#80938](https://github.com/odoo/odoo/pull/80938) của chú đang chết kịch bản test CLA của Odoo.
> 
> Anh có PR update lại ở [odoo#80976](https://github.com/odoo/odoo/pull/80976) nhé

@lathuat1997 sau khi PR mới của anh được merged thì chú rebase lại pr kia để pass qua runbot của Odoo nhé

2021-12-07 14:29 UTC, lathuat1997 commented
> > @lathuat1997 lần trước anh đăng ký sai email của chú với Odoo (thiếu chữ `l`) nên PR [odoo#80938](https://github.com/odoo/odoo/pull/80938) của chú đang chết kịch bản test CLA của Odoo.
> > Anh có PR update lại ở [odoo#80976](https://github.com/odoo/odoo/pull/80976) nhé
> 
> @lathuat1997 sau khi PR mới của anh được merged thì chú rebase lại pr kia để pass qua runbot của Odoo nhé

vâng anh

2021-12-16 02:16 UTC, davidtranhp commented
@lathuat1997 https://github.com/odoo/odoo/pull/80938/files#r767513540

2021-12-16 11:04 UTC, lathuat1997 commented
@davidtranhp @leotranviindoo em dùng luôn PR này để merge code mới từ Odoo được không ạ

2021-12-16 11:06 UTC, leotranviindoo commented
> @davidtranhp @leotranviindoo em dùng luôn PR này để merge code mới từ Odoo được không ạ

Nên làm PR merge từ upstream riêng, vì trong đó có nhiều commits khác không chỉ có mỗi vụ purchase này.

2021-12-16 11:12 UTC, lathuat1997 commented
> > @davidtranhp @leotranviindoo em dùng luôn PR này để merge code mới từ Odoo được không ạ
> 
> Nên làm PR merge từ upstream riêng, vì trong đó có nhiều commits khác không chỉ có mỗi vụ purchase này.

vâng anh, vậy em close PR này anh nhé

2021-12-16 13:23 UTC, closed without merging