[V13][I18N] base: restranslate state to vietnamese
Viindoo/odoo pull request #130
Opened 2022-01-15 04:26 UTC by hoangvanhieu96

PR này để làm gì:

- Dịch lại `state` thành `Trạng thái`
- [Ticket :4565](https://viindoo.com/web#id=4565&model=helpdesk.ticket&view_type=form&cids=1&menu_id=)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-01-24 04:31 UTC, davidtranhp requested changes

2022-01-24 04:31 UTC, davidtranhp commented on odoo/addons/base/i18n/vi.po
> +msgstr "Trạng thái"
Chỗ này chắc phải fix cả code Odoo vì nhãn `State` được dùng chung cho cả các chỗ mang ý nghĩa Bang / Tỉnh. Ví dụ:

Đây là nghĩa "Trạng thái"
```
#: model:ir.model.fields,field_description:base.field_base_partner_merge_automatic_wizard__state
```
Đây là nghĩa "Bang / Tỉnh"
```
#: model:ir.model.fields,field_description:base.field_res_partner__state_id
```

2022-01-24 04:37 UTC, hoangvanhieu96 commented on odoo/addons/base/i18n/vi.po
> +msgstr "Trạng thái"
@davidtranhp Vâng ạ

2022-02-18 05:04 UTC, davidtranhp commented
Thay thế bởi PR này: https://github.com/odoo/odoo/pull/84512

2022-02-18 05:04 UTC, closed without merging