[I18N][15.0] project: update translation
Viindoo/odoo pull request #178
Opened 2022-02-28 01:32 UTC by lnkphm

Description of the issue/feature this PR addresses:
- https://github.com/Viindoo/customer-pecc3/issues/45

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-03-01 10:34 UTC, davidtranhp requested changes

2022-03-01 10:34 UTC, davidtranhp commented on addons/project/i18n/vi.po
> +msgstr "<u>Mốc dự án</u>"
```suggestion
msgstr "<u>Mốc</u>"
```

2022-03-01 10:34 UTC, davidtranhp commented on addons/project/i18n/vi.po
> +msgstr "Theo dõi chi phí và lợi nhuận từ các dự án của bạn"
Profit mới là Lợi nhuận.
Profit = Revenue - Cost
```suggestion
msgstr "Theo dõi chi phí và thu nhập từ các dự án của bạn"
```

2022-03-02 04:12 UTC, lnkphm commented on addons/project/i18n/vi.po
> +msgstr "Theo dõi chi phí và lợi nhuận từ các dự án của bạn"
@davidtranhp em sửa lại các mục trên rồi anh nhé

2022-03-02 13:23 UTC, merged