[FIX] hr: Fix error when an internal user opens the department's list view
Viindoo/odoo pull request #239
Opened 2022-03-31 03:39 UTC by phamgiang2510

When an internal user (without any HR groups) open the departments list view (by clicking 'Search More' on a many2one field, for example), an Access Error appears because of the 'total_employee' field. It is computed by calling 'read_group' on the model 'hr.employee', which normal internal user does not have the right to access on.
This PR solves the issue by overriding the 'read_group' method on 'hr.employee' model.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-04-01 04:46 UTC, daththp commented
@phamgiang2510  fail rb

2022-04-01 09:42 UTC, davidtranhp requested changes
Sao không cho compute_sudo vào `total_employee = fields.Integer(compute='_compute_total_employee', string='Total Employee')`? Số lượng nhân viên của một phòng ban không phải thông tin nhạy cảm và cần phần quyền nên sudo chỗ compute này là hợp lý hơn

2022-04-01 10:11 UTC, phamgiang2510 commented
> Sao không cho compute_sudo vào `total_employee = fields.Integer(compute='_compute_total_employee', string='Total Employee')`? Số lượng nhân viên của một phòng ban không phải thông tin nhạy cảm và cần phần quyền nên sudo chỗ compute này là hợp lý hơn

@davidtranhp e nghĩ xử luôn ở `read_group` gốc thì sau này nếu có code thêm đoạn nào cần `read_group` vào `hr.employee` thì cũng chạy luôn ạ

2022-04-01 10:38 UTC, davidtranhp commented
> > Sao không cho compute_sudo vào `total_employee = fields.Integer(compute='_compute_total_employee', string='Total Employee')`? Số lượng nhân viên của một phòng ban không phải thông tin nhạy cảm và cần phần quyền nên sudo chỗ compute này là hợp lý hơn
> 
> @davidtranhp e nghĩ xử luôn ở `read_group` gốc thì sau này nếu có code thêm đoạn nào cần `read_group` vào `hr.employee` thì cũng chạy luôn ạ

Có vẻ sai sai và không chính tắc cho lắm. Tiện nhưng liệu có rủi ro gì không? Chắc để nghĩ tiên liệu rủi ro mất nhiều time hơn nên em sửa lại thành compute_sudo cho nhanh nhé.

2022-04-02 02:00 UTC, phamgiang2510 commented
> > > Sao không cho compute_sudo vào `total_employee = fields.Integer(compute='_compute_total_employee', string='Total Employee')`? Số lượng nhân viên của một phòng ban không phải thông tin nhạy cảm và cần phần quyền nên sudo chỗ compute này là hợp lý hơn
> > 
> > 
> > @davidtranhp e nghĩ xử luôn ở `read_group` gốc thì sau này nếu có code thêm đoạn nào cần `read_group` vào `hr.employee` thì cũng chạy luôn ạ
> 
> Có vẻ sai sai và không chính tắc cho lắm. Tiện nhưng liệu có rủi ro gì không? Chắc để nghĩ tiên liệu rủi ro mất nhiều time hơn nên em sửa lại thành compute_sudo cho nhanh nhé.

vâng anh

2022-04-04 04:41 UTC, phamgiang2510 commented
@davidtranhp a ơi merge giúp e con này với ạ

2022-04-06 02:56 UTC, phamgiang2510 commented
> @davidtranhp a ơi merge giúp e con này với ạ

@davidtranhp a ơi :v

2022-04-06 06:27 UTC, nhung-vu commented
@davidtranhp anh ơi, anh merge giúp em phần này với ạ
cc @phamgiang2510 @Y-E-N-G-U-Y-E-N @trangdtmt

2022-04-06 07:52 UTC, merged

2022-04-06 07:59 UTC, daththp commented
LGTM