[i18n]website_event_website_event_track:Translate wishlist field and start on Events
Viindoo/odoo pull request #336
Opened 2022-06-02 03:12 UTC by Hung412

Description of the issue/feature this PR addresses:
https://viindoo.com/web#id=6196&model=helpdesk.ticket&view_type=form&cids=1&menu_id=89
Current behavior before PR:
- Start dịch là Kết thúc, End không có bản dịch
- chưa dịch wishlist
Desired behavior after PR is merged:
- Dịch Start thành Bắt đầu, End thành Kết thúc
- Dịch wishlist thành Danh sách yêu thích 
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-02 07:15 UTC, davidtranhp requested changes

2022-06-02 07:15 UTC, davidtranhp commented on addons/website_event_track/i18n/vi.po
> +msgstr "Danh sách yêu thích của"
Chỗ này nó hiển thị chỗ nào trên giao diện em? Và ý nghĩa của nó là gì? Cho anh cái hình chụp giao diện nhé.

2022-06-02 07:19 UTC, Hung412 commented on addons/website_event_track/i18n/vi.po
> +msgstr "Danh sách yêu thích của"
@davidtranhp Dạ vâng anh đợi em chút ạ

2022-06-02 08:08 UTC, Hung412 commented on addons/website_event_track/i18n/vi.po
> +msgstr "Danh sách yêu thích của"
![test](https://user-images.githubusercontent.com/102200922/171576680-6e8c1de2-720a-4c7f-806e-b446b88f453a.jpeg)
Dạ đây anh ạ, 2 chỗ khoanh đỏ là 2 chỗ em được yêu cầu sửa lại bản dịch ạ @davidtranhp

2022-06-03 03:32 UTC, davidtranhp commented on addons/website_event_track/i18n/vi.po
> +msgstr "Danh sách yêu thích của"
Ý nghĩa của cái "Wishlisted By" là gì em? Anh không hiểu. Mà nếu em cũng không hiểu giống anh thì chắc không thể dịch được :laughing:

2022-06-03 03:43 UTC, Hung412 commented on addons/website_event_track/i18n/vi.po
> +msgstr "Danh sách yêu thích của"
@davidtranhp Dạ để em tìm hiểu lại ạ

2022-06-03 04:22 UTC, Hung412 commented on addons/website_event_track/i18n/vi.po
> +msgstr "Danh sách yêu thích của"
@davidtranhp Anh ơi cái Wishlisted By ấy là danh sách những người đăng kí ấn yêu thích buổi diễn thuyết đấy ạ, nên em đề xuất dịch thành "Được yêu thích bởi" hoặc chỉ đơn giản là "Danh sách yêu thích" thôi ạ

2022-06-03 05:44 UTC, davidtranhp commented on addons/website_event_track/i18n/vi.po
> +msgstr "Danh sách yêu thích của"
Ở nút ấy nó có số. Giả sử có data và ấy là số 10 thì khi đọc thì nó sẽ thành "10 Được yêu thích bởi" hoặc "10 SL người yêu thích". Nghe có vẻ không giống tiếng Việt lắm.

2022-06-03 06:04 UTC, Hung412 commented on addons/website_event_track/i18n/vi.po
> +msgstr "Danh sách yêu thích của"
@davidtranhp vậy anh nghĩ sao về 10 lượt yêu thích ạ

2022-06-03 06:31 UTC, davidtranhp commented on addons/website_event_track/i18n/vi.po
> +msgstr "Danh sách yêu thích của"
Anh nghĩ "Lượt yêu thích" OK

2022-06-03 06:32 UTC, Hung412 commented on addons/website_event_track/i18n/vi.po
> +msgstr "Danh sách yêu thích của"
@davidtranhp Dạ vâng anh, để em sửa lại ạ

2022-06-03 06:35 UTC, davidtranhp requested changes
Nhân tiện em rà soát lại phần dịch tiếng Việt của cả 2 module website_event và website_event_track, xem thiếu chỗ nào thì bổ sung. Cách dịch:
1. Cần dịch theo kiểu để người dùng phần mềm có thể hiểu được.
2. Chỗ nào mà không chắc chắn thì bỏ qua, giữ nguyên hiện trạng.

Đây cũng là cơ hội để em tìm hiểu kỹ nghiệp vụ các module này

2022-06-03 06:37 UTC, Hung412 commented
> Nhân tiện em rà soát lại phần dịch tiếng Việt của cả 2 module website_event và website_event_track, xem thiếu chỗ nào thì bổ sung. Cách dịch:
> 
> 1. Cần dịch theo kiểu để người dùng phần mềm có thể hiểu được.
> 2. Chỗ nào mà không chắc chắn thì bỏ qua, giữ nguyên hiện trạng.
> 
> Đây cũng là cơ hội để em tìm hiểu kỹ nghiệp vụ các module này

@davidtranhp Dạ vâng anh, em sẽ rà soát lại ạ

2022-06-03 09:06 UTC, Hung412 commented
> Nhân tiện em rà soát lại phần dịch tiếng Việt của cả 2 module website_event và website_event_track, xem thiếu chỗ nào thì bổ sung. Cách dịch:
> 
> 1. Cần dịch theo kiểu để người dùng phần mềm có thể hiểu được.
> 2. Chỗ nào mà không chắc chắn thì bỏ qua, giữ nguyên hiện trạng.
> 
> Đây cũng là cơ hội để em tìm hiểu kỹ nghiệp vụ các module này

Em đã thêm phần dịch một số chỗ ở cả 2 module, anh review cho em với ạ @davidtranhp

2022-06-04 02:04 UTC, merged