[I18N][13.0] project: additional translation
Viindoo/odoo pull request #367
Opened 2022-06-18 04:22 UTC by sang250399

- [ ] `project`: Bổ sung dịch trên 13.0

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-06-18 06:30 UTC, davidtranhp requested changes
Em chỉ sửa những chỗ cần sửa thôi nhé. Tránh các thay đổi vi phạm bản quyền cũng như các thay đổi không cần thiết.

2022-06-18 06:30 UTC, davidtranhp commented on addons/project/i18n/vi.po
> -#
Đừng "chém" những thứ này đi.
1. Phải ghi nhận công sức đóng góp của cồng chứ?
2. Thay đổi này dẫn đến khi merge từ upstream sẽ tạo conflict

2022-06-18 08:41 UTC, sang250399 commented on addons/project/i18n/vi.po
> -#
Dạ vâng, e bổ sung lại ạ

2022-06-20 02:48 UTC, Thaotran0967 commented on addons/project/i18n/vi.po
> +" Người dùng có dự án > cấp quyền truy cập quản trị viên vẫn có thể truy cập dự án này và các nhiệm vụ của dự án, ngay cả khi họ không phải là thành viên rõ ràng trong danh sách theo dõi.\n"
Người dùng có quyền Quản trị viên/Dự án vẫn có thể truy cập dự án này và các nhiệm vụ của dự án, ngay cả khi họ không phải là thành viên rõ ràng trong danh sách theo dõi.\n"

2022-06-20 02:49 UTC, Thaotran0967 commented on addons/project/i18n/vi.po
> +"- Người dùng nội bộ được mời: khi được cấp quyền theo dõi một dự án, người dùng nội bộ có quyền truy cập vào tất cả các nhiệm vụ thuộc dự án đó mà không có sự phân biệt. Nếu không, họ sẽ chỉ có quyề
..Nếu không, họ sẽ chỉ có quyền truy cập vào các nhiệm vụ cụ thể họ được theo dõi.

@sang250399

2022-06-20 02:59 UTC, Thaotran0967 commented on addons/project/i18n/vi.po
> +"Trong mọi trường hợp, người dùng nội bộ không có quyền truy cập dự án vẫn có thể truy cập một nhiệm vụ, miễn là họ được cung cấp URL tương ứng (và họ là một phần của những người theo dõi nếu dự án l
Trường hợp này chị đang check lại vs Odoo nhé 
https://github.com/odoo/odoo/pull/92897/files
@sang250399

2022-06-20 03:21 UTC, sang250399 commented on addons/project/i18n/vi.po
> +"Trong mọi trường hợp, người dùng nội bộ không có quyền truy cập dự án vẫn có thể truy cập một nhiệm vụ, miễn là họ được cung cấp URL tương ứng (và họ là một phần của những người theo dõi nếu dự án l
oki c

2022-06-23 15:18 UTC, davidtranhp commented on addons/project/i18n/vi.po
> +"Trong mọi trường hợp, người dùng nội bộ không có quyền truy cập dự án vẫn có thể truy cập một nhiệm vụ, miễn là họ được cung cấp URL tương ứng (và họ là một phần của những người theo dõi nếu dự án l
Sao @sang250399 không chủ động check? Người làm kỹ thuật lại phải chờ người không biết kỹ thuật check vấn đề kỹ thuật thì... 😆

2022-06-23 15:31 UTC, royleviindoo commented
@sang250399 anh thấy Odoo đã merged PR `https://github.com/odoo/odoo/pull/92897`, em xem PR này có cần thiết nữa không nhé

2022-06-24 01:10 UTC, sang250399 commented
> @sang250399 anh thấy Odoo đã merged PR `https://github.com/odoo/odoo/pull/92897`, em xem PR này có cần thiết nữa không nhé

dạ PR này vẫn cần a ạ. Vì hiện tại bản 13.0 của cty mình file `vi` chưa update lại dịch theo odoo ạ

2022-06-24 01:13 UTC, sang250399 commented on addons/project/i18n/vi.po
> +"Trong mọi trường hợp, người dùng nội bộ không có quyền truy cập dự án vẫn có thể truy cập một nhiệm vụ, miễn là họ được cung cấp URL tương ứng (và họ là một phần của những người theo dõi nếu dự án l
> Sao @sang250399 không chủ động check? Người làm kỹ thuật lại phải chờ người không biết kỹ thuật check vấn đề kỹ thuật thì... laughing

Dạ em check thì thấy đoạn trong ngoặc odoo dịch hơi khó hiểu so với tính năng. Để em check lại với Odoo ạ.

2022-07-09 01:32 UTC, Thaotran0967 commented
@duong77476  PR này c thấy phần dịch ok rồi nhé

2022-07-11 01:38 UTC, duong77476 commented
@davidtranhp Em thấy PR này có thể merged được rồi ạ, cc @royleviindoo @Thaotran0967

2022-07-12 00:58 UTC, merged