[I18N][15.0] hr_holidays: Added translation for 'Time Off'
Viindoo/odoo pull request #393
Opened 2022-07-10 06:27 UTC by linhpt03690

Description of the issue/feature this PR addresses:
https://viindoo.com/web?#id=7197&action=1075&model=helpdesk.ticket&view_type=form&cids=1&menu_id=777

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-07-10 10:04 UTC, davidtranhp requested changes
Cái này anh chưa xem kỹ tính năng mới trên v15 nên không chắc phần dịch này có OK không. Anh chỉ thấy là tiếng Việt nhưng anh đọc vẫn không hiểu lắm :laughing: 

Có lẽ em nên thử mở phần mềm, tìm hiểu kỹ các tính năng của nó, sau đó dịch thì nó sẽ thân thiện với người dùng hơn.

2022-07-10 10:04 UTC, davidtranhp commented on addons/hr_holidays/i18n/vi.po
> +msgstr "<i class=\"fa fa-thumbs-up\"/> Được duyệt"
```suggestion
msgstr "<i class=\"fa fa-thumbs-up\"/> Duyệt"
```

2022-07-10 10:04 UTC, davidtranhp commented on addons/hr_holidays/i18n/vi.po
> +msgstr "CÓ SẴN"
```suggestion
msgstr "KHẢ DỤNG"
```

2022-07-10 10:04 UTC, davidtranhp commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Mức kế hoạch lũy kế"
```suggestion
msgstr "kế hoạch lũy kế của nhân viên"
```

2022-07-10 10:04 UTC, davidtranhp commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Các lũy kế"
```suggestion
msgstr "Lũy kế"
```

2022-07-10 10:04 UTC, davidtranhp commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Số lũy kế"
```suggestion
msgstr "SL lũy kế"
```

2022-07-10 14:40 UTC, linhpt03690 commented
> Cái này anh chưa xem kỹ tính năng mới trên v15 nên không chắc phần dịch này có OK không. Anh chỉ thấy là tiếng Việt nhưng anh đọc vẫn không hiểu lắm laughing
> 
> Có lẽ em nên thử mở phần mềm, tìm hiểu kỹ các tính năng của nó, sau đó dịch thì nó sẽ thân thiện với người dùng hơn.

dạ vâng, lắm đoạn em dịch nghe chưa được mượt mà thật. đọc cái anh gợi ý nghe khác hẳn. Để em hiệu chỉnh lại ạ.

2022-07-12 04:10 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Hành động cần thiết"
giữ lại bản dịch này em nhé @linhpt03690

2022-07-12 04:12 UTC, linhpt03690 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Hành động cần thiết"
dạ vâng anh @vietphuong10

2022-07-14 07:07 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Lưu trữ phân bổ nhân viên"
```suggestion
msgstr "Lưu trữ cấp phát nhân viên"
```

2022-07-14 07:10 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Nhấp vào nút 'Chỉnh sửa' để thêm các quy tắc mới."
```suggestion
msgstr "Nhấp vào nút 'Sửa' để thêm các quy tắc mới."
```

2022-07-14 07:12 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +"Đây là thời gian mà nhân viên không nghỉ."
```suggestion
"Chỉ lũy kế cho thời gian làm việc của nhân viên. "
"Đây là thời gian mà nhân viên không nghỉ."
```

2022-07-14 07:13 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Tỷ suất"
```suggestion
msgstr "Tỷ lệ"
```

2022-07-14 07:15 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Trình tự được tạo tự động theo delta thời gian bắt đầu."
```suggestion
msgstr "Trình tự được tạo tự động theo thời gian bắt đầu."
```

2022-07-14 07:16 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "đã nghỉ"
```suggestion
msgstr "Đã nghỉ"
```

2022-07-14 07:17 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +"Nhập cho mọi khoảng thời gian"
```suggestion
"Số giờ / số ngày sẽ tăng lên trong Thời gian nghỉ được chỉ định "
"Nhập cho mọi khoảng thời gian"
```

2022-07-14 07:17 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +"cấu hình cấp phát, hủy và tạo một cấp phát mới."
```suggestion
"Cấp phát này đã chạy một lần, bất kỳ sửa đổi nào sẽ không có hiệu lực "
"đối với số ngày được cấp phát cho nhân viên. Nếu bạn cần thay đổi "
"cấu hình cấp phát, hủy và tạo một cấp phát mới."
```

2022-07-14 07:19 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Bảng tin nghỉ"
```suggestion
msgstr "Bảng thông tin nghỉ"
```

2022-07-14 07:20 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Phân tích thời gian nghỉ theo nhân viên và loại nghỉ"
```suggestion
msgstr "Phân tích thời gian nghỉ theo nhân viên và kiểu nghỉ"
```

2022-07-14 07:24 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Bạn phải là người quản lý của %s\\ để chấp thuận việc nghỉ phép này"
```suggestion
msgstr "Bạn phải là người quản lý của %s để chấp thuận việc nghỉ phép này"
```

2022-07-14 07:24 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Bạn phải cung cấp tỷ suất lớn hơn 0 trong các cấp kế hoạch lũy kế"
```suggestion
msgstr "Bạn phải cung cấp tỷ lệ lớn hơn 0 trong các cấp kế hoạch lũy kế"
```

2022-07-14 15:06 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Loại giá trị gia tăng"
```suggestion
msgstr "Kiểu giá trị gia tăng"
```

Còn sót mấy từ này, dùng từ kiểu thay cho từ loại nhé. Em sửa nốt phần này nữa là xong.

2022-07-14 15:09 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +"Không thể tìm thấy phân bổ loại %(left_type)s cho khoảng thời gian được yêu cầu "
```suggestion
"Không thể tìm thấy cấp phát của kiểu %(left_type)s cho khoảng thời gian được yêu cầu "
```

2022-07-14 15:10 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +"Bạn có một số cấp phát cho loại cấp phát và khoảng thời gian cấp phát đó.\n"
```suggestion
"Bạn có một số cấp phát cho kiểu cấp phát và khoảng thời gian cấp phát đó.\n"
```

2022-07-14 15:11 UTC, linhpt03690 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Loại giá trị gia tăng"
dạ vâng anh

2022-07-14 15:11 UTC, vietphuong97 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Phân bổ trên"
```suggestion
msgstr "Cấp phát trên"
```

2022-07-14 15:12 UTC, vietphuong97 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "<span class=\"o_stat_text\">Phân bổ</span>"
```suggestion
msgstr "<span class=\"o_stat_text\">Cấp phát</span>"
```

2022-07-14 15:13 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +" type_numquest_unit"
`Trường cho phép xem thời lượng cấp phát theo ngày hoặc giờ tùy thuộc vào type_request_unit`

2022-07-14 15:16 UTC, vietphuong10 commented on addons/hr_holidays/i18n/vi.po
> +msgstr "Đa nhân viên"
```suggestion
msgstr "Nhiều nhân viên"
```

2022-07-27 02:32 UTC, merged