[I18N][15.0] google_recaptcha: translate
Viindoo/odoo pull request #409
Opened 2022-07-20 02:31 UTC by hoangtiendung070797

Ticket: [7279](https://viindoo.com/web#id=7279&menu_id=89&cids=1&model=helpdesk.ticket&view_type=form)

PR dịch theo yêu cầu ticket. Em làm cho nhà mình trước vì đang cần gấp. Phần dịch sẽ được bổ sung cho Odoo trên transifex sau

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-07-20 09:11 UTC, royleviindoo commented on addons/google_recaptcha/i18n/vi.po
> +msgstr "Yêu cầu không hợp lệ hoặc không đúng định dạng."
@hoangtiendung070797 mất công dịch thì dịch hết đi em, tránh trường hợp sau lại lại nhận được ticket tương tự

2022-07-20 09:12 UTC, hoangtiendung070797 commented on addons/google_recaptcha/i18n/vi.po
> +msgstr "Yêu cầu không hợp lệ hoặc không đúng định dạng."
@royleviindoo dạ vâng anh

2022-07-21 00:18 UTC, davidtranhp commented
Các nội dung dịch mình làm ở nhà mình thôi. Ko cần lên transifex

2022-07-21 01:14 UTC, hoangtiendung070797 commented
> Các nội dung dịch mình làm ở nhà mình thôi. Ko cần lên transifex

@davidtranhp dạ vâng anh

2022-07-21 07:23 UTC, tranngocson1996 commented
@hoangtiendung070797 fail rồi em. Có mấy commit chậm kìa

2022-07-21 07:40 UTC, hoangtiendung070797 commented
> @hoangtiendung070797 fail rồi em. Có mấy commit chậm kìa

@tranngocson1996 dạ vâng anh

2022-07-21 09:00 UTC, davidtranhp requested changes

2022-07-21 09:00 UTC, davidtranhp commented on addons/google_recaptcha/i18n/vi.po
> +msgstr "ứng dụng."
Dịch sai rồi. Lại chưa mở phần mềm hay mở code xem ngữ cảnh hả?

2022-07-21 09:07 UTC, hoangtiendung070797 commented on addons/google_recaptcha/i18n/vi.po
> +msgstr "ứng dụng."
@davidtranhp em vừa dịch lại rồi ạ

2022-07-21 09:11 UTC, davidtranhp requested changes

2022-07-21 09:11 UTC, davidtranhp commented on addons/google_recaptcha/i18n/vi.po
> +msgstr "áp dụng."
```suggestion
msgstr "được áp dụng."
```
Để tạo ra full sentence là "Chính sách Bảo mật và Điều khoản Dịch vụ được áp dụng."

2022-07-21 09:11 UTC, davidtranhp commented on addons/google_recaptcha/i18n/vi.po
> +msgstr "Chính sách bảo mật"
```suggestion
msgstr "Chính sách Bảo mật"
```

2022-07-21 09:12 UTC, hoangtiendung070797 commented on addons/google_recaptcha/i18n/vi.po
> +msgstr "áp dụng."
@davidtranhp dạ vâng anh

2022-07-21 09:17 UTC, merged