[I18N][15.0] gamification: update Vietnamese translation
Viindoo/odoo pull request #419
Opened 2022-07-21 11:23 UTC by TranThiMAi683

Description of the issue/feature this PR addresses:
https://viindoo.com/web#id=7610&cids=1&model=helpdesk.ticket&view_type=form

Current behavior before PR:
[Steps] 
   1. Truy cập Khóa học 
   2. Kiểm tra thông tin hiện tại của User 
[Actual] 
   'Reach the next rank to improve your status!', 'Reach the next rank and become a Master!', 'Reach the next rank and become a powerful user!', 'Reach the next rank to show the rest of the world you exist.' chưa được dịch
[Expect] 
   Hiển thị đúng với bản 14

Desired behavior after PR is merged:
Dịch các chuỗi 'Reach the next rank to improve your status!', 'Reach the next rank and become a Master!', 'Reach the next rank and become a powerful user!', 'Reach the next rank to show the rest of the world you exist.' sang tiếng Việt

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-07-22 21:46 UTC, davidtranhp requested changes
Anh nghĩ là nên hành văn khác đi. Chứ tiếng Việt này anh sợ người Việt đọc không hiểu

2022-07-22 21:46 UTC, davidtranhp commented on addons/gamification/i18n/vi.po
> +msgstr "tháng này"
No new line at end of file

2022-07-22 21:46 UTC, davidtranhp commented on addons/gamification/i18n/vi.po
> +msgstr "Lỗi gửi SMS"
Cái này ở module sms dịch rồi thì không phải dịch lại ở đây nữa

2022-07-22 21:46 UTC, davidtranhp commented on addons/gamification/i18n/vi.po
> +msgstr "Xuất hiện trong"
Giải thích giúp anh ý nghĩa của chỗ này.

2022-07-22 21:46 UTC, davidtranhp commented on addons/gamification/i18n/vi.po
> +msgstr "Đạt đến cấp bậc tiếp theo để cải thiện trạng thái của bạn!"
Anh nghĩ là nên hành văn khác đi. Chứ tiếng Việt này anh sợ người Việt đọc không hiểu 😄

2022-07-22 22:33 UTC, TranThiMAi683 commented on addons/gamification/i18n/vi.po
> +msgstr "Lỗi gửi SMS"
vâng ạ

2022-07-22 22:33 UTC, TranThiMAi683 commented on addons/gamification/i18n/vi.po
> +msgstr "Đạt đến cấp bậc tiếp theo để cải thiện trạng thái của bạn!"
@davidtranhp em sẽ sửa lại ạ

2022-07-22 22:51 UTC, TranThiMAi683 commented on addons/gamification/i18n/vi.po
> +msgstr "Xuất hiện trong"
@davidtranhp chỗ này là string của field challenge_category cho phép chọn nơi xuất hiện của challenge, em đọc thấy 'Xuất hiện trong Cài đặt/Công cụ Gamification' hợp lý hơn 'Xuất hiện ở Cài đặt/Công cụ Gamification' ạ

2022-07-22 22:56 UTC, davidtranhp commented on addons/gamification/i18n/vi.po
> +msgstr "Xuất hiện trong"
👍

2022-07-25 11:14 UTC, davidtranhp requested changes

2022-07-25 11:14 UTC, davidtranhp commented on addons/gamification/i18n/vi.po
> +msgstr "Đạt đến thứ hạng tiếp theo để trở thành một Thạc sĩ!"
```suggestion
msgstr "Đạt thứ hạng tiếp theo và trở thành Cao thủ!"
```
hoặc giữ nguyên từ Master

2022-07-25 11:14 UTC, merged