[I18N][IMP] website : update vietnamese translation
Viindoo/odoo pull request #468
Opened 2022-08-23 09:00 UTC by huy97852

Description of the issue/feature this PR addresses:

Current behavior before PR:

- [issues#445](https://github.com/Viindoo/odoo/issues/445)

Desired behavior after PR is merged:

* keep a certain word in english for its original meaning:
+) Menu
+) Style
* change field name to CamelCase format
* other small change 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-26 09:38 UTC, huy97852 commented on addons/website/i18n/vi.po
> -msgstr "Chiều rộng nội dung"
bỏ từ nội dung vì nếu cho vào sẽ bị mất chữ

2022-08-27 13:08 UTC, davidtranhp requested changes
Cùng công sửa thì phải xem mặc định nó dịch đã chuẩn chưa. Em chỉ search và replace à?

2022-08-27 13:08 UTC, davidtranhp commented on addons/website/i18n/vi.po
> +"tùy chọn cho các tiêu đề và đuôi trang, nhiều nội dung, màu nền theo ngữ "
```suggestion
"tùy chọn cho các tiêu đề và chân trang, nhiều nội dung, màu nền theo ngữ "
```

2022-08-27 13:08 UTC, davidtranhp commented on addons/website/i18n/vi.po
> +"Một lời giải thích nhỏ về tính năng <br/>tuyệt vời này, bằng những từ T rõ"
```suggestion
"Một lời giải thích nhỏ về tính năng <br/>tuyệt vời này, bằng những từ ngữ rõ"
```

2022-08-27 13:08 UTC, davidtranhp commented on addons/website/i18n/vi.po
> +msgstr "Cài Thêm Tính năng"
```suggestion
msgstr "Thêm Tính năng"
```

2022-08-27 13:08 UTC, davidtranhp commented on addons/website/i18n/vi.po
> +msgstr "Thêm Cột"
```suggestion
msgstr "Thêm Serie"
```

2022-08-27 13:08 UTC, davidtranhp commented on addons/website/i18n/vi.po
> +msgstr "Cài Thêm Tính năng"
```suggestion
msgstr "Cài thêm tính năng"
```

2022-08-27 13:08 UTC, davidtranhp commented on addons/website/i18n/vi.po
> +"Chị là một trong những người mang tính biểu tượng trong cuộc sống, người có "
```suggestion
"Aline là một trong những người mang tính biểu tượng trong cuộc sống, người có "
```

2022-08-27 13:08 UTC, davidtranhp commented on addons/website/i18n/vi.po
> +msgstr "Chặn"
```suggestion
msgstr "Khối"
```

2022-08-28 07:40 UTC, huy97852 commented on addons/website/i18n/vi.po
> +"Một lời giải thích nhỏ về tính năng <br/>tuyệt vời này, bằng những từ T rõ"
> Cùng công sửa thì phải xem mặc định nó dịch đã chuẩn chưa. Em chỉ search và replace à?

@davidtranhp dạ vâng em sửa lại luôn ạ

2022-09-14 07:36 UTC, merged