[I18N][15.0] project, web: Add and improve translations
Viindoo/odoo pull request #478
Opened 2022-08-25 10:04 UTC by mduong9586

Description of the issue/feature this PR addresses: 
Ticket: https://viindoo.com/web#id=8410&menu_id=89&model=helpdesk.ticket&view_type=form
Issue: https://github.com/Viindoo/odoo/issues/445

Module project: Improve translations for issue
Module web: Add missing translation for ticket

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-27 09:16 UTC, davidtranhp requested changes
Em rebase để build lại vì code này có vẻ cũ (61 commits behind)

2022-08-27 10:49 UTC, mduong9586 commented
> Em rebase để build lại vì code này có vẻ cũ (61 commits behind)

Vâng ạ! E đã rebase force push rồi anh ạ

2022-08-28 05:36 UTC, davidtranhp requested changes

2022-08-28 05:36 UTC, davidtranhp commented on addons/project/i18n/vi.po
> +msgstr "Các cộng tác viên"
Không nhất thiết lúc nào số nhiều là cứ phải dịch thành "các". Rất dễ xảy ra trường hợp khi nối text thì nội dung dịch cuối cùng sẽ thành "3 các cộng tác viên" thay vì "3 cộng tác viên:
```suggestion
msgstr "Cộng tác viên"
```

2022-08-28 05:36 UTC, davidtranhp commented on addons/project/i18n/vi.po
> +msgstr "Các thẻ Quản trị"
```suggestion
msgstr "Thẻ Quản trị"
```

2022-08-28 05:36 UTC, davidtranhp commented on addons/project/i18n/vi.po
> +msgstr "Đối tác Thương mại"
```suggestion
msgstr "Thực thể Thương mại"
```
Tìm trong Odoo chỗ nào dịch sai chỗ này thì sửa luôn hộ anh nhé.

2022-08-28 05:36 UTC, davidtranhp commented on addons/project/i18n/vi.po
> +msgstr "Tin nhắn Tùy chỉnh Bị trả lại"
Dịch sai. Và cũng chưa xem tính năng của nó. Em cần tìm hiểu tính năng thì mới dịch đúng được
```suggestion
msgstr "Tin nhắn Trả lại Tùy chỉnh"
```
Cái này em dịch lại ở bên module mail để tránh các module khác sẽ bị sai khi xuất file dịch

2022-08-30 01:14 UTC, mduong9586 commented
@davidtranhp Anh ơi! Em đã check và sửa các files dịch liên quan tới các vấn đề đã nêu trên. Có gì anh review cho em với ạ.

2022-08-30 12:49 UTC, merged