[I18N][15.0] point_of_sale: Update vi.po translation file
Viindoo/odoo pull request #480
Opened 2022-08-26 08:28 UTC by NDTruong-F

Description of the issue/feature this PR addresses:

Current behavior before PR:
- [Issues: 445](https://github.com/Viindoo/odoo/issues/445)

Desired behavior after PR is merged:
- Change to the CamelCase format

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-08-27 09:28 UTC, davidtranhp requested changes
Sửa hộ anh mấy cái sau và rà soát các chỗ khác xem còn chỗ nào nhầm lẫn như vậy thì fix luôn nhé.

Nhớ rebase để runbot có thể xanh. Code cũ của em có lỗi thì phải.

2022-08-27 09:28 UTC, davidtranhp commented on addons/point_of_sale/i18n/vi.po
> +msgstr "Bảng hệ thống Tài khoản"
```suggestion
msgstr "Mẫu Hệ thống Tài khoản"
```

2022-08-27 09:28 UTC, davidtranhp commented on addons/point_of_sale/i18n/vi.po
> +msgstr "Dịch chuyển Tài khoản"
```suggestion
msgstr "Bút toán Kế toán"
```

2022-08-27 09:28 UTC, davidtranhp commented on addons/point_of_sale/i18n/vi.po
> +msgstr "Nhóm Sản phẩm khả dụng tại POS"
Trong phần mềm có 3 nhóm sản phẩm:
1. Product Category: để dùng cho nội bộ (kế toán, kho vận, cung ứng)
2. Public Product Category: để dùng để phân loại sản phẩm cho mục đích phân loại, hiển thị ở website
3. PoS Product Category: để dùng để phân loại sản phẩm cho mục đích phân loại, hiển thị ở PoS
```suggestion
msgstr "Nhóm Sản phẩm POS khả dụng"
```
Fyi, @Viindoo/product @Viindoo/project @Viindoo/is

2022-08-27 09:28 UTC, davidtranhp commented on addons/point_of_sale/i18n/vi.po
> +msgstr "Số dư Trước khi Đóng phiên"
Balance mới là "Số dư"
```suggestion
msgstr "Chênh lệch Trước khi Đóng phiên"
```

2022-08-29 00:59 UTC, NDTruong-F commented
> Sửa hộ anh mấy cái sau và rà soát các chỗ khác xem còn chỗ nào nhầm lẫn như vậy thì fix luôn nhé.
> 
> Nhớ rebase để runbot có thể xanh. Code cũ của em có lỗi thì phải.

Vâng ạ anh!

2022-08-30 12:55 UTC, davidtranhp commented
Rebase giúp anh nhé.

2022-08-31 01:59 UTC, NDTruong-F commented
> Rebase giúp anh nhé.

Dạ, em push lại rồi ạ!

2022-08-31 02:02 UTC, anhbtit commented on addons/sale/i18n/vi.po
> +"giao chứ không phải theo số lượng đặt hàng."
@NDTruong-F Câu này đọc khó hiểu vậy em ?

2022-08-31 02:05 UTC, NDTruong-F commented on addons/sale/i18n/vi.po
> +"giao chứ không phải theo số lượng đặt hàng."
Em bị duplicate ạ, em sửa lại ngay. Em cảm ơn ạ

2022-09-14 07:38 UTC, merged