[I18N][15.0] purchase: fix translation
Viindoo/odoo pull request #512
Opened 2022-09-07 09:41 UTC by huy97852

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

Cấu hình mua hàng
- Phần chú thích của "Đơn đã xác nhận": Yêu cầu quản lý phê duyệt Đơn mua trên tổng tiền tối thiểu -> Yêu cầu người được phân quyền quản trị viên mua hàng trên tổng tiền tối thiểu (Đổi cả tiếng anh)
- Check lại tính năng phần phê duyệt đơn mua để biết là lớn hơn hay lớn hơn hoặc bằng giá tối thiểu đã setting
- Mô tả của "đóng gói sản phẩm" chưa dịch sang tiếng việt
- Phần chú thích của "Khoá đơn hàng đã xác nhận": khóa các đơn đặt hàng -> khóa các đơn mua
- Phần chú thích của "Thoả thuận mua": gọi thầu -> mời thầu

Bảng giá nhà cung cấp
- helpstring trường Delivery Lead Time -> Được sử dụng để tính toán tự động cho viêc lập kế hoạch mua hàng (câu cuối - tiếng việt)
- helpstring trường quality -> Số lượng mua từ nhà cung cấp này để được hưởng ưu đãi về giá. (Tiếng việt)

Nhóm sản phẩm
- Danh mục -> Nhóm Sản phẩm (Ý nghĩa là nhóm sản phẩm)
- Hợp đồng mua hàng - > Thỏa ước Mua hàng (Trong mua hàng rà soát lại agreement -> thỏa ước)
- Type -> Kiểu (trong cả phần mềm)

Kiểu yêu cầu mua hàng
- RFQ -> YCBG
- Chưa dịch chỗ select multiple RFQ
- Helptring kiểu lựa chọn chưa dịch  (Hủy các đơn mua còn lại)
- Dữ liệu cho báo giá mới -> Dữ liệu cho YCBG mới (nhãn)
- Nạp các dòng theo yêu cầu -> sử dụng các dòng theo thỏa ước
- Không tạo dòng RFQ một cách tự đôngKhông tự động tạo các dòng
- nạp số lượng thoe yêu cầu -> Sử dụng số lượng theo thỏa ước
- đặt số lượng một cách  -> Đặt số lượng thủ công

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-08 01:32 UTC, davidtranhp requested changes
Sửa lại giúp anh mấy chỗ như comment dưới đây, đồng thời làm lại commit & commit message theo quy ước em nhé.

2022-09-08 01:32 UTC, davidtranhp commented on addons/product/i18n/vi.po
> +"cho viêc lập kế hoạch mua hàng"
```suggestion
"nhận đơn hàng đến lúc nhận hàng. Được sử dụng để tính toán tự động "
"cho viêc lập kế hoạch mua hàng."
```

2022-09-08 01:32 UTC, davidtranhp commented on addons/purchase/i18n/vi.po
> +msgstr "Quản lý các thỏa ước mua hàng của bạn (mời thầu, đơn đặt hàng)"
Do thuật ngữ blanket order và nghiệp vụ của nó không phổ biến ở VN, chỉ phổ biến nếu có hoạt động ngoại thương. Do vậy, tốt nhất ta vẫn nên giữ chữ gốc blanket order để nếu khách hàng của chúng ta là người có nghiệp vụ và chuyên môn về ngoại thương có thể hiểu.
```suggestion
msgstr "Quản lý các thỏa ước mua hàng của bạn như mời thầu, đơn đặt hàng tổng quát (blanket order)"
```

2022-09-08 02:06 UTC, huy97852 commented on addons/product/i18n/vi.po
> +"cho viêc lập kế hoạch mua hàng"
Dạ vâng ạ

2022-09-08 02:13 UTC, huy97852 commented on addons/purchase/i18n/vi.po
> +msgstr "Quản lý các thỏa ước mua hàng của bạn (mời thầu, đơn đặt hàng)"
Dạ vâng ạ

2022-09-08 02:59 UTC, davidtranhp requested changes

2022-09-08 02:59 UTC, davidtranhp commented on addons/purchase/i18n/vi.po
> +msgstr "Mua sản phẩm theo gói, mỗi gói chứa # đơn vị"
Là sao??? Em đọc tiếng Việt chỗ này em có hiểu không @huy97852

2022-09-08 03:11 UTC, huy97852 commented on addons/purchase/i18n/vi.po
> +msgstr "Mua sản phẩm theo gói, mỗi gói chứa # đơn vị"
dạ em sẽ xem lại rồi sửa luôn ạ

2022-09-08 03:36 UTC, huy97852 commented on addons/purchase/i18n/vi.po
> +msgstr "Mua sản phẩm theo gói, mỗi gói chứa # đơn vị"
Theo em hiểu đoạn này là mỗi loại sản phảm có thể được đóng gói lại thành thùng,bao,... và trong mỗi gói đó chứa một số lượng sản phẩm chưa xác định nên để là # nên em dịch như thế này ạ

2022-09-08 03:52 UTC, davidtranhp commented on addons/purchase/i18n/vi.po
> +msgstr "Mua sản phẩm theo gói, mỗi gói chứa # đơn vị"
Em viết kiểu khác đi vì phương Tây họ ký hiệu # thay cho số, số lượng nhưng người Việt Nam không dùng thế bao giờ. Dẫn đến câu tiếng Việt của em sẽ làm cho người dùng không hiểu. Google Dịch chỉ nên để tham khảo.

2022-09-08 03:57 UTC, huy97852 commented on addons/purchase/i18n/vi.po
> +msgstr "Mua sản phẩm theo gói, mỗi gói chứa # đơn vị"
dạ vâng ạ

2022-09-08 04:02 UTC, Johnson-vu commented on addons/product/i18n/vi.po
> +"cho viêc lập kế hoạch mua hàng"
"cho việc lập kế hoạch mua hàng."

2022-09-10 02:10 UTC, duong77476 commented
@huy97852 b rebase force push đi, mẫy lỗi này đã được fix thì phải

2022-09-10 02:32 UTC, huy97852 commented
> @huy97852 b rebase force push đi, mẫy lỗi này đã được fix thì phải

@duong77476 mình đã force-push lại

2022-09-14 07:54 UTC, merged