[WIP][I18N][15.0] stock_landed_costs: fix translate file
Viindoo/odoo pull request #625
Opened 2023-02-22 02:18 UTC by JudgK204

Ticket:  [[IMP][X20] Bổ sung phần dịch cho Chi phí về kho cho lệnh sản xuất](https://viindoo.com/web#id=37343&menu_id=89&model=helpdesk.ticket&view_type=form)

Description:  fix translation file 'vi'

2023-02-22 02:31 UTC, JudgK204 commented on addons/stock_landed_costs/i18n/vi.po
> -#
@tranngocson1996 a xem giúp e phần này có phải bổ sung gì không, e mới làm PR lên odoo nên chưa rõ ạ

2023-02-22 08:03 UTC, lnkphm requested changes

2023-02-22 08:03 UTC, lnkphm commented on addons/stock_landed_costs/i18n/vi.po
> -#
@JudgK204 các phần trên này để lại giúp anh nhé

2023-02-22 08:03 UTC, lnkphm commented on addons/stock_landed_costs/i18n/vi.po
> +"Plural-Forms: \n"
Tương tự như trên, giữ lại như gốc giúp anh

2023-02-22 08:18 UTC, JudgK204 commented
@lnkphm vâng a

2023-02-27 07:56 UTC, JudgK204 commented
@lnkphm a review cho e PR này với ạ

2023-02-28 01:36 UTC, lnkphm commented
@JudgK204 runbot đang fail rồi, đẩy lại PR giúp anh nhé

2023-03-01 01:57 UTC, closed without merging