[FIX][15.0] mrp: rounding total amounts before splitting
Viindoo/odoo pull request #631
Opened 2023-02-28 01:42 UTC by lnkphm

Description of the issue/feature this PR addresses:
- https://viindoo.com/web#id=10536&cids=1&action=1076&active_id=212&model=helpdesk.ticket&view_type=form

Current behavior before PR:
- This PR fixes issue when sum of values in amounts is not necessary equal to production quantity because of float rounding (like 0.1 + 0.2 != 0.3), so new value is added to amounts even if the difference is insignificant. This will lead to unable to create new MOs from that.

Desired behavior after PR is merged:
- Be able to split MOs with multiple values

Refs:
- https://github.com/odoo/odoo/pull/113346

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-02-28 03:40 UTC, royleviindoo commented
@lnkphm có PR fix cho Odoo chưa em? Fix cho Odoo để Odoo 16 để Odoo tự fwd về 15 nhé

2023-02-28 09:26 UTC, lnkphm commented
@royleviindoo em có làm PR fix cho odoo rồi nhưng chưa thấy phản hồi anh ạ. Em có đính PR ở trên mô tả ấy anh.

2023-03-01 09:04 UTC, davidtranhp requested changes

2023-03-01 09:04 UTC, davidtranhp commented on addons/mrp/models/mrp_production.py
>              elif total_amount > production.product_qty or production.state in ['done', 'cancel']:
Thay vì làm tròn `total_amount` dẫn đến mất giá trị, hãy dùng float_compare để so sánh ở chỗ `if... else...`

2023-03-01 09:10 UTC, lnkphm commented on addons/mrp/models/mrp_production.py
>              elif total_amount > production.product_qty or production.state in ['done', 'cancel']:
@davidtranhp vâng anh, để em check lại theo hướng ấy.

2023-03-01 09:52 UTC, davidtranhp commented on addons/mrp/models/mrp_production.py
>              elif total_amount > production.product_qty or production.state in ['done', 'cancel']:
Chỗ PR bên Odoo, em cần nêu rõ các bước để tái hiện lỗi vì cái này khá là khó hình dung. Cần viết thêm test cho cái trường hợp 4kg kia của em thì chắc chắn nó sẽ review và merge.

2023-03-02 04:05 UTC, lnkphm commented on addons/mrp/models/mrp_production.py
>              elif total_amount > production.product_qty or production.state in ['done', 'cancel']:
@davidtranhp vâng anh

2023-03-06 06:53 UTC, tranngocson1996 commented
@lnkphm mình có quy định không link giữa PR odoo và Viindoo mà em, lần sau cẩn thận nhé

2023-03-06 07:59 UTC, lnkphm commented
> @lnkphm mình có quy định không link giữa PR odoo và Viindoo mà em, lần sau cẩn thận nhé

Vâng anh, lần sau em sẽ để ý phần này.

2023-03-15 10:42 UTC, davidtranhp commented
Odoo đã merge và anh đang cẩu nó về ở đây: https://github.com/Viindoo/odoo/pull/646

2023-03-15 10:42 UTC, closed without merging