[I18N][15.0] stock_landed_costs: fix translate file
Viindoo/odoo pull request #632
Opened 2023-03-01 01:47 UTC by JudgK204

Ticket:  [[IMP][X20] Bổ sung phần dịch cho Chi phí về kho cho lệnh sản xuất](https://viindoo.com/web#id=37343&menu_id=89&model=helpdesk.ticket&view_type=form)

Description: fix translate file vi

2023-03-01 03:44 UTC, JudgK204 commented
@lnkphm a review cho e PR này nhé

2023-03-06 06:20 UTC, lnkphm requested changes

2023-03-06 06:20 UTC, lnkphm commented on addons/stock_landed_costs/i18n/vi.po
> +"PO-Revision-Date: 2023-03-01 01:17+0000\n"
```suggestion

```

2023-03-06 06:20 UTC, lnkphm commented on addons/stock_landed_costs/i18n/vi.po
> +"PO-Revision-Date: 2023-03-01 01:17+0000\n"
Giữ lại dòng này giúp anh nhé

2023-03-06 09:15 UTC, JudgK204 commented on addons/stock_landed_costs/i18n/vi.po
> +"PO-Revision-Date: 2023-03-01 01:17+0000\n"
@lnkphm vâng e đẩy lại rồi đấy ạ

2023-03-07 03:13 UTC, lnkphm commented
@JudgK204 runbot fail rồi chú ơi

2023-03-07 03:36 UTC, JudgK204 commented
@lnkphm vâng chờ fix xong runbot rồi e đẩy lại ạ

2023-03-09 01:43 UTC, JudgK204 commented
@lnkphm runbot xanh rồi, a check lại cho e nhé ạ

2023-03-15 01:43 UTC, merged