[FIX][15.0] mrp: The start date of a manufacturing order is never set.
Viindoo/odoo pull request #714
Opened 2023-07-11 08:21 UTC by hoangtiendung070797

Ticket: [[BUG] MRP: MO không có dữ liệu start date (#48169)
](https://viindoo.com/web#id=48169&cids=1&menu_id=97&model=helpdesk.ticket&view_type=form)

Issues
------
All manufacturing orders are not having a start date

This commit
-----------
- Fix not updating start date on manufacturing orders.
- Migration update data

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-07-11 08:30 UTC, davidtranhp requested changes

2023-07-11 08:30 UTC, davidtranhp commented on addons/mrp/migrations/15.0.2.1/pre-migration.py
> +        SET date_start = (SELECT MIN(date_start) FROM mrp_workorder WHERE production_id = mp.id)
Trailing whitespace should be removed
```suggestion
        SET date_start = (SELECT MIN(date_start) FROM mrp_workorder WHERE production_id = mp.id)
```

2023-07-11 08:44 UTC, hoangtiendung070797 commented on addons/mrp/migrations/15.0.2.1/pre-migration.py
> +        SET date_start = (SELECT MIN(date_start) FROM mrp_workorder WHERE production_id = mp.id)
@davidtranhp yes sir

2023-07-13 08:24 UTC, davidtranhp commented
Thay thế bằng https://github.com/Viindoo/odoo/pull/715

2023-07-13 08:24 UTC, closed without merging