[16.0][i18n] survey: add more vie translation
Viindoo/odoo pull request #756
Opened 2023-09-14 09:57 UTC by nguyenvietlam0640

Description of the issue/feature this PR addresses: [task]()

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-09-18 04:49 UTC, davidtranhp requested changes

2023-09-18 04:49 UTC, davidtranhp commented on addons/survey/i18n/vi.po
> +msgstr "Câu hỏi"
```suggestion
msgstr "SL Câu hỏi"
```

2023-09-18 04:49 UTC, davidtranhp commented on addons/survey/i18n/vi.po
> +"                                <span class=\"text-muted\">Thời gian trung bình</span>"
```suggestion
"                                <span class=\"text-muted\">Thời lượng Trung bình</span>"
```

2023-09-18 04:49 UTC, davidtranhp commented on addons/survey/i18n/vi.po
> +"                                    <span class=\"text-muted\">Đã tham gia</span>"
Ngữ cảnh này là ngữ cảnh ghi nhận số lượng câu trả lời chứ không phải người tham gia đúng ko @nguyenvietlam0640 
```suggestion
"                                    <span class=\"text-muted\">Đã ghi nhận</span>"
```

2023-09-18 05:06 UTC, nguyenvietlam0640 commented on addons/survey/i18n/vi.po
> +"                                    <span class=\"text-muted\">Đã tham gia</span>"
Chỗ này em kiểm tra lại thì vẫn là số lượng người tham gia khảo sát anh ạ. Ở phần tree view của `survey.survey` anh click vào cột registered sẽ ra view của `survey.user_input` anh nhé

[Screencast from 18-09-2023 12:02:25.webm](https://github.com/Viindoo/odoo/assets/106436992/bc5a72ee-d1a2-4ede-8709-62047b3d2dd3)

2023-09-18 06:10 UTC, davidtranhp commented on addons/survey/i18n/vi.po
> +"                                    <span class=\"text-muted\">Đã tham gia</span>"
user input là các bản ghi trả lời khảo sát em à

2023-09-18 06:14 UTC, nguyenvietlam0640 commented on addons/survey/i18n/vi.po
> +"                                    <span class=\"text-muted\">Đã tham gia</span>"
@davidtranhp dạ vâng để em sửa lại

2023-09-18 23:55 UTC, davidtranhp requested changes

2023-09-18 23:55 UTC, davidtranhp commented on addons/survey/i18n/vi.po
> +msgstr "Đã xong, nộp bài"
```suggestion
msgstr "Bây giờ bạn đã hoàn tất, hãy gửi biểu mẫu của bạn"
```

2023-09-23 04:29 UTC, royleviindoo commented on addons/survey/i18n/vi.po
> +"                                    <span class=\"text-muted\">Đã ghi nhận</span>"
```suggestion
"                                    <span class=\"text-muted\">Đã tham gia</span>"
```

2023-09-27 03:52 UTC, royleviindoo commented on addons/survey/i18n/vi.po
> +"                                    <span class=\"text-muted\">Đã tham gia</span>"
```suggestion
"                                    <span class=\"text-muted\">Đã ghi nhận</span>"
```

2023-09-27 03:52 UTC, royleviindoo commented on addons/survey/i18n/vi.po
> +msgstr "<span class=\"text-muted\">Đã tham gia</span>"
```suggestion
msgstr "<span class=\"text-muted\">Đã ghi nhận</span>"
```

2023-09-27 03:53 UTC, merged